# Python basic data types --
1. Python variables
2. Integers and float
3. String
4. Booleans
5. Printing

# Python Basic data types --
1. Data types are the categorisation of data items. Data types represent a kind of value which determines what operations can be performed on that data.
2. **Numeric** -- Any representatin of data which has a numeric value.
    (i) **Integer** -- Positive or negative whole numbers
    (ii) **Float** -- Any real number with a floating-point representation in whicha fractional component is denoted by a decimal symbol.
    (iii) **Complex no.** -- A number with real and imaginary components represented as ***x + yj*** where *x*, *y* are floats and *j* is the square root of -1.
3. **Boolean** -- Data with one of the built-in values *true* or *False*.
4. **Sequence type** -- An ordered collection of similar or different dat types. Python has the following built-in sequence data types --
    (i) **String('')("")("""""")('''''')** -- It is a collection of on ore more characters put in single, double or triple quotes.
    (ii) **List[]** -- A list object is an ordered collection of one or more data items, not necessarily of the same data type, put in square brackets. 
    (iii) **Tuple()** -- An ordered collection of one or more data items, not necessarily of the same data type, put in parantheses.
    (iv) **Dictionary{key:value}** -- An onordered collection of data in *key:value* pairs in enclosed curly brackets.
3. **type()** function -- Python has a built-in function to asscert in the data type of a certain value. The **type()** function tells us about the data type of a particular data.
4. **Mutable** -- Mutable objects are the objects whose values can be changed later on. *List*, *dictionary* are mutable and hence value inside them can be added, deleted, inserted and rearranged.
5. **Immutable** -- Thiose objects whose values cannot be altered after creation, Numbers, strings, tuples are immutable objects.

# Variables --
## Why do we need variables --
Anything we write in code is processed and stored in a random memory address and we do not know the particular memory address. So, in order to reuse a value, we need to give the variable a *reference* which we call a variable.
## Naming variables --
1. We cannot use Python's reserved keywords for naming variables. Ex - **if**, **for**, **while**, etc.
2. Python is case-sensitive. So, x != X.
3. According to pyrthon guide, variable names should be lower-case with words separated by underscores (_) as to improve readability.
4. We cannot have spaces in variabe names. 
5. Special characters can also not be used in naming variables.

## Integers --
The most yet most used data type. We don't need to declare the type of any variable.
If we write x=3, Python will create a variable called **x** which will have **int** as its datatype.
We can see this by writing **type(x)**.

In [3]:
x = 3
type(x)

int

## Float --
If we write x=3.0, Python will create a variable called **x** which will have **float** as its datatype. We can see it by writing **type(x)**.

In [4]:
x = 3.0
type(x)

float

### Performing an arithmetic operation between a float and an integer results in a float automatically.

**Float Continued** --
1. We can use scientific notation (10^x) as follows -- **x = .4e7**
2. Any number bigger than **1.8 x 10^(308)** will be treated as **infinity**.
3. Any number less than **5.0 x 10^(-324)** will be treated as **zero**.


## Floating-point representation --


# String --
1. A string is basically a **sequence of characters**.
2. Even **one character** is called a string.
3. Even an **empty** string is a string.
4. String is identified by a single quotation **('')** or double quotation **("")**. 


5. The statement below will throw a syntax error --
    'I'm a progrmmer'
    because the compiler will assume that the string ended after I as there is a single quotation mark.
    So, the correct way to write the above statement will be --
    "I'm a programmer"

# String Special characters --
1. \b - backspace
2. \f - new page
3. \n - new line
4. \t - new tab

5. If we want to suppress the special characters, simply insert **r or R** at the start of the string.

In [5]:
strr = r"This will not give \t tab space"
print(strr)
strr2 = "This will give tab \t space"
print(strr2)

empt_str = " " # even this is also a string/.

This will not give \t tab space
This will give tab 	 space


In [6]:
"""
Q. Create a variable that contains the following string --
I'm learning "programming"
"""
# Ans - 
str_ = """I'm learning "programming" """
print(str_)

# OR

str__ = "I\'m learning \"programming\""
print(str__)

I'm learning "programming" 
I'm learning "programming"


# String operations --
1. We can add two strings.
2. We cannot multiply two strings.
3. We can multiply a string by an integer. The output is the string repeated the number of times the integer.
4. We can check if a string is in another string using an opertor called **in** operator.
5. Python has a lot of **built-in** functions for every data type.
6. Example --
    (i) **chr()** - converts int to character.
    (ii) **len()** - calculates the length of string.
    (iii) **srt()** - converts to string.
    (iv) **ord()** - converts to integer.

In [7]:
# String addition --
first_str = "Rishi"
second_str = "Thakur"
result_str = first_str + " " + second_str
print(result_str)

Rishi Thakur


In [8]:
# String*int --
print(result_str*3)

Rishi ThakurRishi ThakurRishi Thakur


In [9]:
check = "Rishi Thakur"
first_str in check

True

In [10]:
second_str in check

True

In [11]:
result_str in check

True

In [12]:
space = " "
space in check

True

In [13]:
# write string_name then . at the end and then press tab to see all 
# the functions
print(check.capitalize())

Rishi thakur


In [14]:
print(check.lower())

rishi thakur


In [15]:
print(check.upper())

RISHI THAKUR


In [16]:
len(check)

12

In [17]:
"""
Q. Convert the given string to all capital letters
and calculate it's length.
"""
str_quiz = "convert to all capital letters"
str_capital = str_quiz.upper()
str_len = len(str_quiz)
print(str_capital)
print(str_len)

CONVERT TO ALL CAPITAL LETTERS
30


# String indexing -- 
1. Indexing is done using **[]**.
2. Indexing is **zero-based** -- counting starts from **0** and not **1**.
3. We can also index strings using the reverse order, where **-1** corresponds to the last character in the string.
4. If we use an index bigger than the length of the string, an error will be thrown.

In [18]:
check

'Rishi Thakur'

In [19]:
# printing the last letter.
check[-1]

'r'

In [20]:
# lets try to print an index greater than the length of string --
len(check)

12

In [21]:
# even if we call the index number equal to length of string,
# we will get an error because strings are zero-indexed,
# so if the length is 12, the index of last character is 11
check[12]

IndexError: string index out of range

In [ ]:
check[11]

# String slicing --
1. We use **:** to specify the slice start and end.
2. The end index is not included.

## String stride --
1. By default, stride is one.
2. If we want to change stride, we use another **:**.
3. It is like this -- **[start : end : stride]**.

## String useful functions --
1. **string_name.count("ch")** -- counts the occurences of a character in a string.
2. **string_name.find("ch")** -- returns the index of the first occurence of a particular character.

In [ ]:
"""
Q. Snowball is one of the most famous poems in literature.
It says --
"I made myself a snowball
As perfect as could be.
I thought I'd keep it as a pet
And let it sleep with me.
I made it some pajamas
And a pillow for its head.
Then last night it ran away,
But first it wet the bed.

1. How many times does the poem have 'it' word.
2. How many total characters are in the poem, including spaces and punctuations.
3. Tell the first ocurrence of the word 'it'.
4. Where is the last occurence of the word 'I'.
"""
# Ans --
snowball = "I made myself a snowball\nAs perfect as could be.\nI thought I'd keep it as a pet\nAnd let it sleep with me.\nI made it some pajamas\nAnd a pillow for its head.\nThen last night it ran away,\nBut first it wet the bed."
it_count = snowball.count("it")
print(it_count)
poem_len = len(snowball)
print(poem_len)
it_location = snowball.find("it")
print(it_location)
I_last = snowball.rindex("I")
print(I_last)

# Boolean --
1. Boolean can have one of two values -- **True** or **False**.
2. Any python expression can either be *True* or *False*. So, any Python expression is a Boolean.

# Printing --
1. Syntax of the print function --
        print(object,sep,end,file,flush)
2. By default, the print function prints in the current Python kernel.
3. Can print variables by writing **f** before the quotation marks and writing the variables betweeen curly brackets.

## Format function --
1. Makes printng variables much easier and readable.
2. One of the most-used string functions.
3. Syntax --
        string_name.formaat(value1, value2)

In [ ]:
x=21
print(x)

In [ ]:
# Printing variables --
print(f"The value of x is {x}")

# Python operators --
1. Arithmetic -- Used with numeric values to perform common mathematical problems. [+, -, *, /, %, //, ***]
2. Assignment -- Used to assign values to variables. [=, +=,=+, *=, %=,//=]
3. Comparison -- Used to compare two values. [==, !=, <, <=, >, >=]
4. Logical -- Used to combine conditional statements. [**not**, **or**, **and**]
5. Identity -- Used to compare the objects, not if they are equal,but if they are actually the same object. [**is**, **not is**]
6. Membership -- Used to  test if a sequence is present in an object. [**in**, **not in**]
7. Bitwise -- Used to compare binary numbers. [**&**, **|**, **~**, **^**, **>>**, **<<**]

In [ ]:
2+3

In [ ]:
4-5

In [ ]:
4**2

In [ ]:
10//4

# Floating point problem --
What should be the result of this --
1.1 + 2.2 == 3.3
It should be **True** right?
But, when you run the code, the answer will be **False**.
This is not an error or a problem in Python, but is a limitation of the *hardware*.

In [ ]:
1.1+2.2==3.3

In [ ]:
print(1.1+2.2)

### Logical operators --
What is **True** and **False** for logical operatoes --
1. **False** --
        (i) Zero numerical values - 0.0, 0, 0.0+0
        (ii) Empty Strings
        (iii) Empty objects
        (iv) **None** keyword
2. **True** --
        Anything else rather than the above values is *True* in Python.
        
#### Truthness vs Equality --
If we check the **truthness** of an empty string using the built-in function **bool('')**, we will find it false.
However, if we check the equality with the equality operator, we will also get False, and hence we will be confused.

In [ ]:
print(""==False)
print(""==True)

The main reason why we get both the statements above to be False because we are using comparison operator. And, as a matter of fact, two objects of different data types never compare equal except numerical, and hence **""** is a *string* and **False/True** is a *bool*. So, we will always get False as **String != bool**.

In [ ]:
"""
Q. Use any one of the logical and get the output as True
"""
num1 = 10
num2 = 50
num3 = 14
# Ans --
bool_exp = (num1<num3 and num3<num2)
bool_exp2 = (num1==num2 or num2>(num1+num3))
print(bool_exp)
print(bool_exp2)

### Identity operators --
##### Identity vs equality --
The **equality** operator checks if the **values** are the same.
Whereas, the **is** operator checks if the **variables (objects)** are the same.

In [ ]:
x=100;y=100
print(x==y) ## Equality operator -- comparing values

In [ ]:
print(x is  y) ##Identity operator, comparing variables (MEMORY ADDRESS)

In [ ]:
id(x)

In [ ]:
id(y)

We can see that both the variables are at the same memory address.
This is because in python, any value between **-5** and **256** are stored in the same memory address and the varibables with same value are referenced to the value if they are in the same code block for memory optimisation. 

In [ ]:
# Membership --
str_in = "Rishi Thakur"
"i T" in str_in

In [ ]:
# function to convert int to binary --
p = 30
bin(p)

In [ ]:
q = 10
r = p|q
r

# Python advanced datatypes ---

## 1. Lists[] --
1. List is a collection of items of different data types. It is an ordered sequence of  items.
2. A list object contains one or more data items, not necessarily of the same type, which are separated by commas and enclosed in square brackets[].
3. Syntax -- 
        list_name = [value1, value2, value3, .....]
4. The list is zero-indexed.

## 2. Tuples() --
1. Tuple is a collection of any Python data type, same as the list.
2. Unlike list, tuple is immutable.A tuple object contains one or more data items, not necessarily of the same type, which are separated by commas and enclosed in parantheses().
3. Syntax -- 
        tuple_name = (value1, value2, value3, .....)
4. It is not necessary to enclose the tuple elements in parantheses. The tuple object can include elements separated by a comma without parantheses.

## 3. Sets{} --
1. A set is a collection of data types in Python, same as list and tuple. However, it is not an ordered collection of objects.
2. A set object performs mathematical set operations like union, intersection, difference, etc.
3. A set object contains one or more items, not necessarily of the same data type, which are sepaated by comma and enclosed in curly brackets{}.
4. Syntax --
        set_name = {value1, value2, value3, ....}
5. A set dosen't store duplicate values. Even if an object is added more than once inside the  set, only one copy is held in the set object. Hence, indexing and slicing cannot be done on sets.
5. **set()** function -- Python has a built-in function in which a set object can be constructed out of any sequence such as a string, list or a tuple.
6. A set is mutable.
7. Set dosen't have order.
## 4. Dictionary{k:v} --
1. Dictionary is also a collection of data type. However, it's not an ordered sequence, and it contains **key:value** pairs.
2. One or more **key:value** pairs separated by commas are put inside curly brackets to form a dictionary object.
3. Syntax --
        dict_name = {key1:value1, key2:value2, .....}
4. A number, string, or tuple can be used as a key.
5. A dictinary with a list as a key is not valid, as list is mutable. A list can be used as value though.
6. The same key cannot appear more than once in a dictionary. If the key appears more than once, only the last value of the key will be retained.
7. Key needs to be unique, but two keys can have the same value.
8. Dictionary is not anordered collection, so a value cannot be accessed using an index in square brackets. To fetch a value from the dictionary, we need the assosciated key of that value using the **get()** method. 

## 5. Compound data structure --
1. Python is very flexible in the value of any advanced data type, **other than the set**.
2. We can do the following --

    (i) my_list = [1, (3,4,"a"),6.6,"Str"]
    (ii) my_tuple = (2,34, }{1:56},90, [98,21,43])
    (iii) my_dict = {1:["lost",6], 2:{45:"goat"}}

In [ ]:
"""
Q. Given below is a list with 9 elements.
1. Get the last 4 elements of a list and store them in a diferent list.
2. Get the maximum value of the list and store it in a separate variable.
3. Sort the values of the original list in ascending order.
4. Add the selements from task 3 to the original list.
"""
my_list = [100 , 30 , 2 , 15 , -4 , 3 , 40 , -9 , 10]
last4 = my_list[-4:]
max_val = max(my_list)
sorted_list = sorted(my_list)
added_list = my_list + sorted_list
print(last4)
print(sorted_list)
print(added_list)

## List Slicing and indexing --
A string is actually a **list** of characters.
So, all the rules of strings do aply here.

### **List Slicing** --
1. Zero-based
2. Square brackets todefine it.
3. Comma to separate elements.
4. Colon to slice.

**But this does not make lists and string to be equal**

In [ ]:
# **But this does not make lists and string to be equal**
list_ex = [1,2,3]
list_ex[1]="Rishi"
string_ex = "Python"
string_ex[1] = "R"

# This code will not work because strings are immutable,
# whereas lists are mutable.

In [ ]:
"""
Q. Count how many '4' we have in the provided tuple
and store it in a separate variable.
"""
tuple_4 = (1,6,4,10,2,10,4,"hi",104.2,4)
# Ans --
count_4 = tuple_4.count(4)
print(count_4)

In [ ]:
# Sets do not have an index --
# so this code will surely throw an error
set1 = {1,2,3}
print(set1[1])

In [ ]:
# sets only hold unique values --
set2 = {4,2,1,6,1}
print(set2)

We can add elements in a set using the **add** function.
We can remove elements from a set using the **pop** function.
The **pop** function removes the first element in the set.

In [ ]:
set2
set2.add(8)
print(set2)

In [ ]:
# popping 1 --
set2.pop()
print(set2)

In [ ]:
## checking if a key exists in a dictionary or nor --
dict2 = {1:"one", 2:"two", 3:"three"}
print(1 in dict2)

In [ ]:
## if we want the values of a key of a dictionary, we use the
## get() function.
dict2.get(2)

1. Adding elements in a dictionary - 
dict_name[key] = value

In [ ]:
"""
Q. Create an empty dictionary for the grocery items.
Then add the items as follows --
Apple --> 4
Banana --> 6
Cucumber --> 2
Pizza --> 2
Chocolate --> 3
"""
dict3 = {}
dict3["Apple"] = 4
dict3["Banana"] = 6
dict3["Cucumber"] = 2
dict3["Pizza"] = 2
dict3["Chocolate"] = 3
print(dict3)

In [ ]:
"""
Q. How to access '10000' in the following example --
compound_dict = { 10 : [ 3 , [ 10 , { 3 : 10000 , 2 : 50 } , 3 ] ] , 2: "hi"}

1. compound_dict[3]
2. compound_dict[10,1,3]
3. compound_dict[10][1][1][3]
"""
# Ans --
compound_dict = { 10 : [ 3 , [ 10 , { 3 : 10000 , 2 : 50 } , 3 ] ] , 2: "hi"}
compound_dict[10][1][1][3]

## When to use each datatype ?

#### Lists --
Use **lists** when we do not have any special cases that we want to take care of, and we want our list to be ordered for indexing.
### Tuples --
Use **tuples** only when we are sure that the values inside them should *not* be changed no matter what. So, tuples is the best way to assure that.
### Dictionaries --
Use **dictionaries** when we want to have some sort of relation between some unique variables and other non-unique variables, as we are only concerned with the key.
### Sets --
Use **sets** when we know that any repeated data will be redundant. So, sets can be very efficient in *ignoring* redundant data and **increase** the *performance* of any algorithm.

## Control flow -- 
1. Control flow
2. Conditional Statements -- **if**, **else**, **elif**
3. for loops
4. while loops

## Conditional Statements --
1. By default, statements iin the script are executed sequentially from the first to the last.
2. If the processing logic requires so, the sequential flow can be altered in two ways --
    (i) **Conditional Execution** -- A block of one or more statements will be executed if a certain expression is true.
    (ii) **Repetitive execution** -- A block of one or more statements will be repetitively executed as long as a certain expression is true.
### If --
1. Pytho uses the **if** keyword to implement decision control.
2. **If** Syntax --
        if boolean expression : 
            statement1
            statement2
3. Any boolean expression evaluating True or False appears after the **if** keyword. One or more statements written with the same level of indent will be executed **if** the boolean expression evaluates to be true.
### Else --
1. Along with the *if*, the **else** can be used to define an alternate block of statements to be executed if the boolean expression inside the *if* condidiotn is not true.
2. The indentation and syntax of the **else** is sameas the **if**.

### Iteration, loop --
1. **Iteration** means executing the same block of code over and over again. A programming structure that implements iteration is called a **loop**.
2. There are two types of *iteration* --
    (i) **Indefinite** -- The designated block is executed repeatedly as long as some condition is met.
    (ii) **Definite** -- Th number of times the designated block will be executed is specified explicitly at the time of the loop starts.
    
### For loop --
1. The **for** loop is used with sequence types such as a *list*, *tuple* and a *set*. The body of the **for** loop is executed for each member element in the sequence.
2. Syntax --
    for x in sequence :
        statement 1
        statement 2
        ....
3. The variable *x* in the above syntax refers to the item at 0 index in the given sequence. The statements after the **:** block will be executed. Variable *x* now refers to the next item and repeats the body of the loop until the sequence is exhausted.

### While loop --
1. A program by default, follows a sequential execution of statements. A while loop in Python repeatedly executes a target statement as long as the given condition is true.
2. Syntax --
    while <expression> :
        <statements>
            
3. The controlling expression, **<expression>** typically involves one or more variables that are initialised prior to the loop and then modified somewhere in the loop body.

In [ ]:
# printing a pattern using nested loop --
for i in range(1,10) :
    for j in range(i,10):
        print("*", end=" ")
    print(" ")

In [ ]:
for i in range(1,10,) :
    for j in range(1,i):
        print("*", end=" ")
    print(" ")

In [ ]:
# Conditional Statements with advanced data types --
# We can combine them with if conditions --
if_list = [1,2,4,5.6]
if 2 in if_list :
    print(if_list)

In [ ]:
# We can also check more than one conditions at the same time too --
x=10;y=54;k=90
if x>y and k>y :
    print(z)
elif y>x and k>y:
    print(y)
else :
    print(x)

In [ ]:
"""
Q. Imagine that we are creating a simple guessing game where
the user guesses a number and we either tell him that his guess
is too low, too high or correct.
Implement this game in python using if, else, elif.
create all the three cases as an output.
"""
num1 = 20
guess1 = 10
if guess1>num1 :
    print("Too high")
elif guess1<num1 :
    print("Too low")
else :
    print("Correct")

guess2 = 91
num2 = 89
if  guess2>num2 :
    print("Too high")
elif guess2<num2 :
    print("Too low")
else :
    print("Correct")

guess3 = 420
num3 = 420
if guess3>num3 :
    print("Too high")
elif guess3<num3 :
    print("Too low")
else :
    print("Correct")

In [ ]:
## Conditional Statements with advanced data type --
# if with list --
listt = [1,2,3,4]
if 2 in listt :
    print(listt)

In [ ]:
"""
Q. Imagie that you are scraping data from the web and
storing it in a list. Now, every two minute to stop to check if
the collected data contains three tokens or not.
The three tokens are 'start', 'mid', 'end'
If you found them, print - 
Found them! Stop the code!.
If not, print -
Not yet. Still searching...
"""
web_list = ["start", 10313, 1415, "afvav", "vbagaga", "mid", 3.415, {"A":12121}, {"xava":11} , 1.21, "end"]
# Ans - 
web_list
if "start" in web_list and "mid" in web_list and "end" in web_list :
    print("Found them! Stop the code!")
else :
    print("Not yet. Still Searching..")

## Iterables --
1. If we want to run an operation iteratively, we use loops.
2. **for** loop runs for a specific **pre-defined** number of iterations.
3. We *iterate* over **iterables**.
4. **Iterables** are python objects that return one or more of its elements per iteration.
5. **Iterables** can be --
    (i) Files
    (ii) Dictionaries
    (iii) Lists
    (iv) Sets
    (v) Tuples
    (vi) Strings

### Range function --
We can use **range** function to loop over a range of values.
Ex -- 
    for element in range(10)  :
        print(element)
        
The above code will run 10 times or the loop will iterate over 10 values.
We can also set the start, end and step for the range function --
    

In [ ]:
#range function
for element in range(1,10,2) :
        print(element)
        
#|The above code will run - 1, 3, 5, 7, 9

In [ ]:
# printing elements of a list using for loop --
my_list = [1,2,3,"Rishi", "Payday", "Remnant"]
for element in my_list :
    print(element)
print("Done")

In [ ]:
## using range function --
for element in range(20):
    print(2*element)

In [ ]:
"""
Q. What will be the output of the following code below --
Option 1 --
1:10
20:5
3:2

Option 2 --
0
1
2

Option 3 --
1
20
3

Option 4 --
10
5
2
    
"""
dict_quiz = {1:10, 20:5, 3:2}
for i in dict_quiz :
    print(i)
    
# because by default, the loop will iterate over keys and not values.

### "end" parameter in "print()"
1. By default, the **print()** function ends with a new line. 
2. Python's print() function comes with a parameter **end**. By default, the value of this parameter is '\n' i.e. new line. But we can end a print statement with any *character* or *string* using the **end** parameter.

In [ ]:
# Example of end --
print("Welcome to " , end = 'end') 
print(" Python course")

In [ ]:
"""
Q. Print the following pattern using loops --
1
1 3
1 3 5
1 3 5 7 
1 3 5 7 9
"""
# Ans 1 --
for i in range(1,11,2):
    for j in range(1,i+2,2):
        print(j, end=" ")
    print(" ")
    
    
# Ans 2 --
for i in range(1,10,2):
    for j in range(1,i+1,2):
        print(j, end=" ")
    print(" ")

#### While loops --
1. While loops run until a **condition** is no longer satisfied.
2. We need to make sure that the stop conditon in a while loop must be met, otherwise we will have an **infinite loop**.


## While vs For ---
1. We prefer **while** ***over*** **for** when we don't know how many iterations we have.

In [ ]:
# Using while over for example --
## if we want to multiply numbers in a list cumilitatively --
## until the result is bigger than 100
## we can only achieve this using while and not for --
my_list = [10,2,30,5,12]

i = 1 # we need to initialise a variable before using while loop
current_element = 0
while i<100:
    i*=my_list[current_element]
    current_element+=1 # we need to also declare the increment/decrement
print(i)

# Control flow paer 2 --
1. Break statements
2. Continue statements
3. Zip keyword
4. Enumerate keyword
5. List comprehensions
6. How to build a dictionary using loops

### Break statement ---
If we want to **break** from a for/while loop if some condition happens, we use the break statement.

In [ ]:
## break statement with for loop example --
break_list = [1, 2, 54, "pi", "stop", 4.21, "#,$"]
for element in break_list:
    print(element)
    if element == "stop":
        print("The loop will not continue")
        break
        
# running this code, we will see that the loop didn't print --
# the remaining elements after stop

In [ ]:
## break statement with while loop example --
buck = [1, 2, 54, "pi", "stop", 4.21, "#,$"]
index = 0
while index<len(buck):
    element = buck[index]
    print(element)
    if element == "stop":
        print("The loop will stop")
        break
    index+=1

In [ ]:
"""
Q. Remember web_list from previous excercise.
Now, instead of checking if the 3 tokens are in the list or not,
we can stop the list once we have those 3 tokens.
Your task here is to loop over the elements and use the *break*
statement to stop the loop once we found the end.
if you found it, print --
Found them!, Stop the code!
If not, print --
Not yet. Still searching..
"""
web_list = [ "start" , 10313 , 1415 , "afvav", "vbagaga", "mid", 3.415, {"A":12121}, {"xava":11} , 1.21, "end"]
for element in web_list :
    if element == "end":
        print("Found them! Stop the code!")
        break
    else :
        print("Not yet. Still searching..")

### Continue statement ---
If we want to **skip some iterations** from a *for/while* loop if some condition happens, we use **continue** statement.

In [ ]:
### Continue statement with for loop example --
my_list4 = [1, 2, "stop", 3.42, 6.9]
for element in my_list4:
    if element == "stop":
        print("The loop will skip stop")
        continue
    print(element)

In [ ]:
# continue with for loop --
loop_list = [1, 2, 3, 54, "stop", 5, "end", "stop", 3.14]
for element in loop_list :
    if element == "stop" :
        print("Stop skipped")
        continue
    print(element)

In [ ]:
"""
Q. What is the output of the following code ---
1.  3
    2
    1

2. Infinite loop from 3 and decreasing
3. Infinite loop from 3 and increasing
4.  3
    4
    5
    6

4.  3
    2
    1
    1
    1
    infinite ones
"""
"""
counnt = 3
while counnt <= 6 :
    print(counnt)
    if counnt == 1 :
        continue
    counnt -=1
"""
#  Ans - option 4

In [ ]:
"""
Q. Imagine that we have a list of ages that we scraped from a website.
Now, we want to store only the even ages so we can perform some
analysis on them. 
Use for, if and continue statements to create a new list with even ages.
"""
list_ages = [10 , 11 , 19 , 7 , 8 , 24 , 91 , 74 , 25 , 53 , 41 , 50 , 63 , 86]
ages_even = []
for element in list_ages :
    if element%2!=0 :
        continue
    ages_even.append(element)
print(ages_even)        

## Zip function --
1. Zip function maps iterables to iterators.
2. What if we have a couple of **iterables** and we want to create **iterables** from them? -- We use the **zip** function to achieve that task.
3. What if we want to iterate over *multiple* iterables at the same time, we also use the zip function.

In [ ]:
# Zip function example --
first_list = [1, 2, "stop", 3.41, 3.14]
second_list = [4, "two", "skip", "four", "pi"]
zipped_list = zip(first_list, second_list)
print(zipped_list)

In [ ]:
# above -- we can see that an iterator was created by the zip function.
# In order to print the iterator, we need to convert the iterator to 
#an iterable again.
# printing the iterator --
print(list(zipped_list))

In [ ]:
# iterating over multiple iterables --
first_list
second_list
for e1,e2 in zip(first_list,second_list) :
    print(e1,e2)

In [ ]:
# another example --

list_01 = [1, 3, 65, 90] ## iterable
list_02 = [5, 1, 54, 98] ## iterable
zip_list = zip(list_01,list_02) ## iterator
print(zip_list) ## will still print the location of the object
 ## converting back to iterable to print the values

In [ ]:
# So, using the zip function, we merged two lists into a single list.

In [ ]:
for i1, i2 in zip_list :
    print(i1,i2)

In [ ]:
"""
Q. What will be the output of the following code --

Option 1 --
1 "quiz" 6
2   4    8
10  12   5

Option 2 --
1 "quiz" 6
2   4    8

Option 3 --
Error
"""
quiz_list = [1, 2, 10, 5]
quiz_dict = {"quiz":3, 4:9}
quiz_tuple = (6, 8, 12)
for x,y,z in zip(quiz_list,quiz_dict,quiz_tuple) :
    print(x,y,z)

In [ ]:
"""
Q. Imagine that you have two lists, 
the first one contains student's names and
the second one contains their grade.
Now, we want to link each student with their grade in a separate dict.
Use 'for', 'dictionaries' and 'zip'
"""
# Ans 1 --
student_names = ["Michael", "John", "Isra", "Munro"]
student_grades = [80, 53, 90, 100]
zipp_name_grade = zip(student_names,student_grades)
name_grade = dict(zipp_name_grade)
print(name_grade)

In [ ]:
# Answer 2 --
student_names2 = ["Michael", "John", "Isra", "Munro"]
student_grades2 = [80, 53, 90, 100]
name_grade2 = {}
for x,y in zip(student_names2,student_grades2) :
    name_grade2[x]=y
print(name_grade2)    

## Enumerate function --
1. Enumerate function is a zip function but with a counter.
2. What if we want to iterate over one iterable and one **counter** at the *same time*? -- we use the **enumerate** function.

In [ ]:
# Enumerate function --
enu_list = ["GCC", "minGW", "conda", "jdk"]
for i, element in enumerate(enu_list) :
    print(i,element)

In [ ]:
enut_list = enumerate(enu_list)
# we need to convert the iterator same way we did for the zip function.
print(list(enut_list))

In [ ]:
"""
Q. What will be the output of the following code ---
Option 1 -
           10
            5
           13
 
Option 2 - 
           0
           1
           2

Option 3 -
           10 0
           5  1
           13 2

Option 4 -
           0 10
           1 5
           2 13
"""
list_quixx = [10, 5, 13]
for index, value in enumerate(list_quixx):
    print(value, index)

In [ ]:
"""
Q. Imagine we have a list of people's names and another list of their 
salary. 
Now, we want to link each person with his salary in a new list as follows --
"Person Name $2000"
So, we want each element in the new list to be a string that contains
both the persons name along his/her salary.
Use 'string manipulation', 'enumerate' and 'for loop'
"""
# Ans --
names = [ "Rachael Green", "Goodfellow Ian", "Tedd Crock", "Mina Joseph"]
salaries = [10260 , 41571 , 71211 , 52141 , 35781]
names_salaries = []
for i,j in enumerate(names):
    x = j + "$" + str(salaries[i])
    names_salaries.append(x)
print(names_salaries)

## List comprehension --
1. It is a way of writing and creating lists in a more compact and efficient way.
2. If we want to build a list faster, we use **list comprehension**

In [ ]:
# creating a list normally --
my_list_normal = []
for element in range(10):
    my_list_normal.append(element)

# creating using list comprehension --
my_list_comp = [element for element in range(10)]

print(my_list_normal)
print(my_list_comp)

In [ ]:
""" 
What is the output of the following code --
1. Error
2. [(0,5),(1,6),(2,7),(3,8),(4,9)]
3. [0,1,2,3,4]
4. (5,6,7,8,9)
5. [0,5,1,6,2,7,3,8,4,9]
6. [[0,5],[1,6],[2,7],[3,8],[4,9]]
"""
list_comp = [(index,value) for index,value in enumerate(range(5,10))]
print(list_comp)

In [ ]:
"""
Imagine that we have a dictionary that contains the students's names and grades.
Now, we want to filter out students who passed - above 50 - 
and get their names in a new list.
Use list comprehension to create the list in a single line
of code using list comprehension.
"""
students_dict = {"Joel Corry" : 70,"James Bond" : 90,"Fatma Ahmed": 20,"Lily Saqr"  : 94, "Ahmed Yan"  : 40,}
passed_students = [name.split()[0] for name,x in students_dict.items() if x > 50]
print(passed_students)

## Python functions --
1. In Python, a function is a group of related statements that perform a specific task.
2. Functions in python --
    (i) Help function
    (ii) Deleting functions
    (iii) Variable scope (Local vs Global)
    (iv) Doc strings
3. A **function** takes some *inputs*, do some *logic* on them, and return an *output*.
4. The function can take multiple inputs and also return an output.
5. Giving an input to a function is also optional. Or the function can take some input and provide no output.
6. Suppose we want to calculate the sum of two variables, but we want to repeat the process multiple times, then we need to convert our code to a **function**.

## Python help function --
Python has hundreds of built-in functions.
Each function can have one or more inputs and outputs. But we do not need to remember any of them.

In [ ]:
## Example of help ---
## If we write help(function_name), python will tell us
## about the specific function.
## Ex --
help(print)

In [ ]:
help(zip)

In [ ]:
help(int)

## Defining functions --

### Function header --
1. Python uses **def** to define the function.
2. Functions can have multiple inputs and/or outputs.
3. Function header example --
    def function_name(input1, input2) :
4. We can have **optional input** by assigning the value of the variable in the function header.
    Example for point 4 -
    This code *will* throw an error if we don't provide **x** or **y** in the function body, but *will not* throw an error if we don't provide **z** in the function body --
    def multiply(x, y, z=1) :
    
### Function body --
1. The function body is indented in a code block, like loops and conditional statements.
2. We can return one or more outputs using the **return** keyword.
3. Example of a complete function with body amd header --
    def multiply(x,y) :
        result = x*y
        return result
        
## Function naming -- 
1. We cannot use spaces or special characters in a function name.
2. We cannot use Python keyword or built-in function's names for naming our own function.

## Function calling --
1. We can call the function as follows --
    func_name(input_1, input_2)

In [ ]:
# Making our own function that multiplies 2 int,float
def multiplyy(x,y):
    result = x*y
    return result
res=multiplyy(6,9)
print(res)

In [22]:
"""
Q. Implement a function that just prints 'Hello World'.
The function takes no inputs and returns no outputs.
It should just print 'Hello World'
"""
def hello():
    printt="Hello World"
    return printt

## or 

def hello2():
    print("Hello World")

hello2()
hello()

Hello World


'Hello World'

In [23]:
"""
Q. Implement a function that takes two inputs 
and returns their sum.
"""

def addition(x,y):
    additn = x+y
    return additn
addition(6,7)

13

In [24]:
"""
Q. Implement a function that takes two inputs, a number and a
power that the number should be raised to.
"""
def power(x,y):
    expo = x**y
    return expo
power(4,2)

16

In [25]:
"""
Q. Implement a function that takes two lists as input - 
One contains student's names and  one contains their grades.
The function should link (zip function) elements of the lists and give a
dictionary as an output.
"""
student_names = [ "Micheal Ford", "John Buch" , "Isra Raul", "Messi Ronaldo"]
student_grades = [80, 53, 90, 100]
def link_name_grade(student_names,student_grades):
    linked_dict = {}
    for x,y in zip(student_names,student_grades) :
        linked_dict[x]=y
    print(linked_dict)
    return linked_dict

In [26]:
"""
Q. Implement a function that takes a list of integers 
and another input called even_or_odd to specify --
if  we want the even or odd numbers.
If even_or_odd is false, then we will choose the even numbers.
If even_or_odd is true, then we will choose the odd numbers.
"""
numbers = [10, 20 , 17 , 13 ]
even_or_odd = True
filtered_list = []
def filter_even_odd(numbers, even_or_odd) :
    for element in numbers :
        if element%2!=0 :
            filtered_list.append(element)
    return filtered_list

## Variable scope --
1. Not all variables can be accessed all the time.
2. There is a scope for each variable, either **global** or **local**.
3. **Global** variables can be accessed or modified from anywhere in the code.
4. **Local** variables can only be accessed from specific functions.

In [27]:
## Local variable --
# Notice the following code --
def multiply3(x,y):
    result=x*y
    return result
print(result)

## If we print result, we will get an error, because the
## variable is the local variable of the function
## and we were trying to access it globally.

NameError: name 'result' is not defined

In [ ]:
## Globalvariable --
## See this code --
result=5
def multiply4(x,y):
    result=x*y
    return result
## now we have two different variables 'result'
## if we print result, we will get 5 because we called the
## global variable which was defiined nefore the function.
print(result)
## To call the local result, we will have to call the function.
multiply4(5,2)

However, we can **force** a variable inside a function to be global using the **global** keyword.

In [ ]:
## forcing variable to be global --
result2 = 5
def multiply5(x,y):
    global result2
    result2=x*y
    return result2

## now if we call result after we call the function using any inputs,
## we will get same answer --
print(multiply5(4,5))
print(result2)

In [ ]:
## We can see above, we get the outpput of the result2 equal to whtever the function 
## will give for the variable.

In [ ]:
# if we call the function again with different value,
# the global result will also chnge --
print(multiply5(5,10))

print(result2)

In [ ]:
"""
Q. Whar will be the output of the following code --

1. 0
2. 6
3. Error
"""
ball_count = 0
def count_balls():
    ball_count +=6
    return ball_count
print(count_balls())

## We get this error message because we cannot modify 
## global variables in functions without --
## passing them as arguments

## Doc strings --
1. Doc Strings, short for **Documentation Strings**, is crucial for documenting Python Functions.
2. Very simple, use triple quotes ("""""") in the line after the function header.

In [ ]:
## Doc Strings Example --
def funct(x,y):
    """
    Multiply two numbers and return their result.
    """
    result=x*y
    return result
funct(5,5)

## Error Handling and User Input --
1. Error handling
2. User inputs
3. Syntax errors
4. Exceptions

## Error handling --
Almost anything in the world can have error.
### Types of Errors --
1. **Syntax Errors** -- 
    (i) Syntax errors are like grammatical errors in English
    (ii) The code won't run under any circumstances.
2. **Exception** --
    (i) Can hapen even if there are no syntax errors.
    (ii) The code will stop if some condition happen.
    (iii) We need to catch and handle this condition, so the code won't stop.

## User input --
Many applications work by taking user input. So, in many cases, we cannot prevent the user from using the application incorrectly.

Example of an error occured due to user input --
If the user gives a **string** input to the function multiplying two integers. We know that string multiplication is not possible and hence, we will surely get an error in this case. 
So, we need to handle the expected incorrect inputs.

## Taking user input --
We can read the keyboard input using the Python's built in **input** function.
The function waits until the user inserts the inputs and submits it by clicking **enter**.
We can also provide a help message for the user.

In [ ]:
## Taking user input --
x = input("Enter an integr value - ")
print(x)

but we need to remember a point that the input function always takes value input as a string no matter what the type of input.

In [ ]:
print(type(x))

We can see that we gave an integer input but it was stored as a string
So we need to attach a converter before the input function itself.

In [ ]:
# Taking integer input --
z = int(input("Enter any number - "))
print(z)
print(type(z))

We can see above that now our input was stored as an int.

In [ ]:
"""
Q. What is the output of this code --
1. <class 'int'>
2. <class 'float'>
3. <class 'str'>
"""
user_input = input("Enter a number")
print(type(user_input))

## Ans - <class 'str'>

In [ ]:
"""
Q. Take two numerical user inputs and print their sum.
"""
input1 = int(input("Enter a number - "))
input2 = int(input("Enter 2nd number - \n"))
summ = input1+input2
print(f"The sum is {summ}")

## Syntax errors --
1. Syntax errors, also known as **parsing** errors, as the Python interpreter parse the whole code to convert it into byte code before being executed.
2. Syntax errors are the most commom errors and are easy to understand and overcome.
3. Syntax errors are **unrelated** to corectnes of the code's **logic**.
4. Either way, we need to fix the syntax error to even run.
5. If there are multiple syntax errors in the code, the code will stop and highlight the first one only.

6. The syntax error message gives us four pieces of information about the error --
    (i) The file name
    (ii) Then there's an exponent or the carnet sign(^)
    (iii) The line number where the error has occured
    (iv) The error message

In [ ]:
"""
Q. Which of  the following will throw a syntax error --

1. x1 = 2
2. x 1 = 2
3. x_1 = 2
"""
# Ans -  # Option 2

## Exceptions --
1. They are also called run-time errors.
2. They happen when there are no syntax errors in the code, but the code failed in some cases.
3. Example of a common run-time error -- if we have a function that divides two numbers, if the denominator is zero, then the code will fail and stop.
### Types of Exceptions --
1. Built-in exceptions -- like the ZeroDivisionError
2. User defined exceptions

In [ ]:
## The output of this code will throw an error -
## ZeroDivisionError -- at line 7
def div(x,y):
    divisionn = x/y
    return divisionn
print(div(5,2))
print(div(5,0))
print("Hello")

We can see that the code after getting an error at line 7 stopped the code and "Hello" at line 8 was not printed.

In [ ]:
## User defined exception example --
num1 = int(input("Enter a number"))
num2 = int(input("Enter another number"))
if num1>num2 :
    raise Exception("First num should be less than second num")

### Assertion --
There is another way to raise an exception.
We can use the word **assert** for detecting bugs more clearly in our code.

In [ ]:
## Assertion example --
num_1 = int(input("Enter a num"))
num_2 = int(input("Enter another num"))
assert num_1<num_2

## Difference in Assert vs Raise --
### raise -- 
1. Use to raise an  exception.
2. To be used with **try** and **except**.
3. raise can also be used to re-raise current error to pass it up the stack to see if something else can handle it.
### assert -- 
1. Use to raise an exception if a condition is not met.
2. **assert** is used when we want to "stop" the script based on a certain condition and return something to help debug faster.

In [ ]:
## assert example --
list_error = ["a", "b", "x"]
assert "x" in list_error, "x is not in list"
print("passed")

list_error1 = ["a", "b", "c"]
assert "x" in list_error1, "x is not in the list"
print("passed")

In [ ]:
## NameError --
## When we call an object which is undefined
print(go)

In [ ]:
## TypeError --
    ## when we do something which is not possible --
    ## Example -- adding int to string
2 + '2'

In [ ]:
## Defining our own EXCEPTION --
x = 10
y = 20
if x<y :
    raise Exception("This is incorrect")
print("Hello")

The above message - "Hello" at line-6 was not printed because the user-defined exception occured before.

In [ ]:
## Defining the same above EXCEPTION using "assert" --
x1 = 10
y1 = 20
assert x>y
print("Hello")

In [ ]:
"""
Q. What is the exception in this code --
1. ZeroDivisionError
2. NameError
3. RuntimeError
4. KeyError
"""
dict_quiz = {1:10, 20:3}
print(dict_quiz[2])

## Ans -- Key Error

## Handling Exceptions --
1. Exceptions break the code -- any exception will **break** the code and any lines after the exception will not be executed.|
2. Therefore, we need to catch and handle the errors.
### try & except ---
1. We handle exceptions using a block of **try** and **except**.
2. Inside the **try body**, we write the code that we want to **execute**, but we suspect *it may throw an error*.
3. Inside the **except body**, we write the code that *should be executed* if an exception occurs.

In [ ]:
## After modifying the division function which was giving
## us a ZeroDivisionError using try and except --
def divi(x,y):
    try :
        result=x/y
    except :
        result="Can't divide by zero"
    return result
print(divi(5,2))
print(divi(5,0))
print("Hello")

We should always be cautious and specific with exceptions. Otherwise, we might catch exceptions that we do not want. Or we might **neglect bugs** that should be handled.
We need to be cautious because using generic except hides all the errors!

In [ ]:
## Example of a bug being hidden by except --
def divi2(x,y):
    try:
        assert x==y
        result=x/y
    except:
        result="Can't divide by zero."
    return result
print(divi2(5,2))
print(divi(5,0))
print("Hello")

As we can see above, that 5!=2 and hence our assertion failed and so it was counted as an errorand hece if x!=y, we will always get an exception even if the function inputs are correct.

### Handling multiple exceptions --
1. We can have as many exceptions as we want. 
2. Just like conditional statements, the first exception is the only one that will be executed, and other will be ignored.

In [ ]:
## multiple exceptions example ---
def divi3(x,y):
    try:
        result=x/y
        assert x>=y
    except ZeroDivisionError:
        result="Cannot divide by 0"
    except AssertionError:
        print("Error, x is less than y")
    return result
print(divi3(6,3))
print(divi3(4,8))
print(divi3(5,0))
print("Hello")

### try, except and else ---
Jut like the if condition, we can add **else** clause while handling errors.


In [ ]:
## try, except, else example --
def divi4(x,y):
    try:
        res=x/y
    except ZeroDivisionError :
        res="Can't divide by 0"
    else:
        print("Else")
    return res
print(divi4(6,3))
print(divi4(4,8))
print(divi4(5,0))
print("Hello")

### Finally clause ---
1. The **finally** clause runs whether the try statement produces an exception or not.
2. If a finally clause is present, the finally clause will execute as the last task before the try statement completes.
3. If the exception is not handled by an except clause, the exception is **re-raised after the finally** clause has been executed.
4. If the try statement reaches a break, continue, or return statement, the finally clause will execute just prior to the break, continue or return statement's execution.
5. If a finally clause includes a return statement, the returned value will be the one from the finally clause's return statement, not the value from the try's clause's return statement.

In [ ]:
## finally example --
def bool_return():
    try :
        return True
    finally :
        return False
bool_return()

We can see that we had no exceptions so the try statement was not executed and hence the finally statement was executed before try.

In [ ]:
## finally example 2 --
# the code below will be re-executed after the finally,
# so, an error will be thrown in the third case.
def divide2(x,y):
    try:
        result=x/y
    except ZeroDivisionError:
        print("Can't divide by zero")
    else:
        print(f"Result is {result}")
    finally:
        print("Executing finally clause")
divide2(2,1)
divide2(2,0)
divide2("2","1")

In [ ]:
"""
Q. The function below will not work if we give 0 as the second input/
Use try and except to handle this exception.
"""

# Edit the code above so that the user gets a warning for 
# ZeroDivisionError
# using try and except --
def test_div(x,y):
    try:
        dividee=x/y
    except ZeroDivisionError :
        dividee="Can't divide by 0"
    return dividee

print(test_div(24,4))
print(test_div(4,0))

In [ ]:
"""
Q. What will be the output of the following code --

1. There is an exception

2. There is an exception
   Inside finally clause

3. No Problem

4. No Problem
   Inside finally clause
"""
# code --
x=10
try :
    x>5
except:
    print("There is an exception")
else:
    print("No Problem")
finally:
    print("Inside finally clause")
    
## Ans --
# Option 4

## Python Advanced functions --
1. Lambda functions
2. Functions *args and **kwargs
3. Iterators
4. Generators and Yield keyword
5. Map function
6. Filter function

## Lambda function --
1. Lambda functions are basically one-line functions.
2. The division function we discussed before can be simplified into one line using the lambda function as follows --

a. Normal function --
def div(x,y):
    return x/y
print(div(3,2))

b. Lambda function of the same ---
div = lambda x,y : x/y
print(div(3,2))

3. So, syntax of lambda function -
We first use the lambda keyword, then the function variables, then the colon then the function body.
func_name = lambda input1,input2 : function body

4. Lambda functions are mainly used for **small simple** functoins.
5. It can also be used as an **argument** for **higher-order** functions.

## Higher order functions --
1. **Higher order functions** are functions that take *functions* as **arguments**.
2. **filter** and **map** functions are two examples of higher order functions.

In [ ]:
## Example of a lambda function --

# writing a normal function --
def multiplyy1(x,y):
    return x*y
print(multiplyy1(4,3))

# writing lambda function for the same --
multiplyy2 = lambda x,y : x*y
print(multiplyy2(3,4))

In [ ]:
"""
Q. What will be the lambda function of the following function --

Option 1 --
def multiply(x,y) : res= x*y return res

Option 2 --
def multiply(x,y) : res = x*y ; return res

Option 3 --
multiply = lambda x,y ; x*y
"""

## Ans -- Option 3 
multiply = lambda x,y : x*y
multiply(5,4)

In [ ]:
"""
Q. Implement a lambda function that takes one input.
Use this function to add six to the variable you create.
"""
# Ans --
add6 = lambda z : z+6
add6(6)

## Function args and kwargs --

### Python input flexibility --
Sometimes, we don't know beforehand how many inputs a function should take.
For example -- we can have a multiplication function that should multiply all its input, which can be 2,3,4 or more.
The best way to do this is to use a list as the function input -- this is the way in most programming languages.
However, in python, we have a more elegant way to do it.

## function args ---
However, instead of doing it as we did above, there is a more elegant and pythonic way to do that, and we don't need to worry to define a list -- this is by using **args** as an argument.
The **asterisk** is called as the **unpacking operator**.

In [ ]:
## Using a list to multiply all ---
def mult_all(input_list):
    result=1
    for i in input_list:
        result*=i
    return result
my_list = [1, 2, 3, 4, 5]
print(mult_all(my_list))

In [ ]:
## Using args to do the same --
def mult_all2(*args):
    result=1
    for i in args:
        result*=i
    return result
print(mult_all2(1,2,3,4,5))

Notice that we pass the inputs as **positional arguments** -- **tuple** , and not a *list*.
Also, note that we do not need to write **args** always, this is just a convention.

In [ ]:
## Example that we need not compulsorily write args --
def not_args(*x):
    result=1
    for i in x:
        result*=i
    return result
print(not_args(1,2,3,4,5))

## function kwargs --
1. If you have keywords or named arguments, then you can use **kwargs**, short for *keyword arguments*.
2. We can define it by using double asterisk, which is also an unpacking operator.

In [ ]:
## kwargs example --
def display(**kwargs):
    for k,e in zip(kwargs.keys(),kwargs.values()):
        print(k,e)
display(x="Red",y="Dead",z="Redemption",a="2")

Notice that we pass arguments a a **dictionary**.
Also, not that we do not need to write **kwargs**, this is just a convention.

#### The function input ordering --
The correct function input ordering is as follows --
1. Standard input --
    (i) Required input
    (ii) Optional input
2. Positional args (*args)
3. Keyword input (**kwargs)

In [ ]:
## demo function with input  ordering --
def demo(x,y, z=3, *m, **n):
    print("Hello")

## here --- 
## x,y are the standard required inputs
## z is the standard optional input
## *m is the positional args
## **n is the keyword input. 

In [ ]:
## args example -- 
def args_demo(*s):
    for i in s:
        print(i)
args_demo(3,21,"g",2.3)

In [ ]:
## kwargs example --
def kwargs_demo(**l):
    for i,j in zip(l.keys(),l.values()):
        print(i,j)
kwargs_demo(one='one',two='two')

In [ ]:
## defining a function with incorrect order --
## we will get an error 

def incorrect_order(y=1,x):
    return 0

In [ ]:
"""
Q. What is the correct function header --
Option 1 --
def app(input_1, input_2, input_3=10, *input_4, **input_5)

Option 2 --
def app(input_1=10, input_2, input_3, *input_4, **input_5)

Option 3 --
def app(*input_1, input_2=10, input_3, input_4, **input_5)
"""

# Ans -- Option 1

In [ ]:
"""
Q. Implement a funciton that can take any number of inputs
and multiply all of them.
Hint - use args
"""
## Ans --
def multiply_all(*l):
    i = 1
    for x in l:
        i*=x
    return i
print(multiply_all(1,2,3))

In [ ]:
"""
Pi wants anything between 7000 and 10000 rupees! So help Pi write a function that will check whether the amount his sister offers to give him (variable, sis) is within the required range of rupees.
If the number less than 7000, show the message, "Ahem, can you rethink this number please?".
If the number is greater than 10000, show the message, "Wow sis! You are a queen".
If the number is within the range, show the message, "Cool, thanks sis! x rupees will certainly help."
"""

In [ ]:
def money(money):
    ttal = money+sis
    if ttal > 10000 :
        print("Wow")
    elif 7000<ttal<10000:
        print("Will help")
    elif ttal<7000:
        print("I'm broke")
    return ttal
sis = 6000
money(5000)
money(500)

## Iterators --
1. We said that we iteratre over iterables -- python objects that return one or more of its elements per iteration.
2. **Iterators** are the python objects that contain the **data stream** and we can traverse through their elements.
3. We can construct iterables using the **iter** keyword. 
4. We can make an iterator from any kind of iterablesuch as lists, tuples, dictionaries, sets.
5. We can iterate over iterators element-by-elemnt using the **next** keyword.
6. Unlike iterables, a iterator starts where it has stopped.
7. Also, if the iterator dosen't have any more element left, it will throw an error called **StopIteration**.

In [28]:
## constructing an iterator --
list_2 = [1, 2, 67, "Rishi", 'rdr2']
iteratorr = iter(list_2)
print(iteratorr)
print(next(iteratorr))
print(next(iteratorr))

1
2


In [29]:
## StopIteration ---
list_3 = [1,2]
iterator1 = iter(list_3)
print(next(iterator1))
print(next(iterator1))
print(next(iterator1))

1
2


StopIteration: 

In [ ]:
# We cannot access the elements of an iterator --
my_list43 = [21,42,854,569,76147]
my_Iter = iter(my_list43)
print(my_Iter[2])

**Lazy Evaluation**  -- It is a concept in programming that sometimes we do not want to evaluate an expression unless we call it.

Ex -- When we call an element from a list -- my_list[0], then the whole list is called into RAM, but when we deal with iterators, only the element which we call using **next** is called and hence, iterators are not subscriptable.

We have a library named **itertools** that has all iterator functions.

In [ ]:
"""
Q. What will be the output of this code?

1. 10
2. 3
3. 14
4. StopIteratorError
"""
list_quizo = [10, 3, 15]
list_quizo_iter = iter(list_quizo)
var_1 = next(list_quizo_iter)
print(next(list_quizo_iter))

# Ans -- 3
## because 10 was iterated for var_1 and hence, the iterator 
## started where it left i.e. 3

## Generators --
1. We can create Python iterators using functions.
2. We can also create Python *functions using iterators -- and these functions are called **generators**.
3. Same as iterators, whenever the generator is called, it starts from where it left.
## Yield --
1. The key difference between regular functions and generators is the **yield** keyword.
2. Yield makes the generators return values **one at a time**.
3. **yield** replaces the **return** keyword.

### Advantages of generators over normal functions --
1. **Lazy** way to build iterables.
2. Using generators, we can deal with **out-of-memory** problems.
3. Generators are faster than normal functions, as there is no need to read the whole iterables when we want to perform some functions.

In [ ]:
## normal function --
def reverse_normal(data):
    for i in range(len(data)-1, -1, -1) :
        print(my_list43[i])
my_list43 = [21,42,854,569,76147]
reverse_normal(my_list43)

In [ ]:
## generator function of the above function --
def reverse_generator(data):
    for index in range(len(data)-1, -1, -1):
        yield my_list43[index]
# calling the function --
varr = reverse_generator(my_list43)

In [ ]:
print(varr)

In [ ]:
next(varr)

In [ ]:
next(varr)

In [ ]:
next(varr)

In [ ]:
next(varr)

In [ ]:
"""
Q. Which of the following is not the valid reason 
to use generators?

1. They are a lazy way to build iterables.
2. They make the code shorter.
3. They deal with out-of-memory problems.
4. They are faster than normal functions.
"""
## Ans -- Option 2

## Map function --
1. Syntax of **map** function --
    map(func, *iterables)
2. The asterisk means there can be more than one iterables.
3. The map function basically applies the input function o the input iterable.
### Points to be noted before using map function --
1. The function must have number of **inputs** *equal* to the number of **iterables**.
2. The map function returns a *generator* that can be applied using the list built-in function.
3. The function can be a *normal* or a *lambda* too.
4. It's better to use lambda function with map function as it is more preferred and Pythonic way to write the code.

In [ ]:
# normal fnction --  
def addFive(my_list):
    output_list = []
    for i in my_list:
        i+=5
        output_list.append(i)
    return output_list
my_list = [4,5,6,7]
addFive(my_list)

In [ ]:
# doing the same with the map function --
def addFive_map(element):
    return element+5
outt = map(addFive_map, my_list)

In [ ]:
type(outt)

In [ ]:
list(outt)

In [ ]:
# using map with lambda function --
# my_list = []
output_map = map(lambda i : i+5, my_list)

In [ ]:
list(output_map)

In [ ]:
# using map function to convert integer list to float list.
int_list = [21, 27, 90, 101]
float_list = map(float, int_list)
print(float_list)
list(float_list)

In [ ]:
# using map function to raise elements of a list to some power.
work_list = [2, 3, 5, 10]
pow_list = [2, 2, 2, 2]
expo_list = map(pow , work_list, pow_list)
list(expo_list)

In [ ]:
"""
Q. Use the map function to create a list that contains the no. of
occurences of the letter 'n' in each element in the provided list.
Use - map, lambda, count, list.
"""
input_list = ['What we think, we become', 'Every moment is a fresh beginning.', 'Change the world by being yourself', 'Hate comes from intimidation, love comes from appreciation', 'If I’m gonna tell a real story, I’m gonna start with my name.', 'Oh, the things you can find, if you don’t stay behind.']
mapped_list = list(map(lambda element: element.count("n"), input_list))
print(mapped_list)

## Filter function --
1. Instead of applying a function on all the elements in the iterable, **filter** selects specific elements from the iterable based on the condition in the function.
2. Syntax -- 
    filter(func, iterable)
3. Unlike map, **filter** can only work on **one** iterable.
### Points to be noted while using filter function --
1. The function must return a **boolean iterable**.
2. Like map, the filter returns a **generator**.

In [ ]:
list_grades = [20, 70, 100, 50, 60, 34, 70]
def pass_grade_normal(list_grades):
    pass_grade_list = []
    for element in list_grades:
        if element>50:
            pass_grade_list.append(element)
    return pass_grade_list
pass_grade_normal(list_grades)

In [ ]:
## filter example --
grades = [20, 70, 100, 50, 60, 34, 70]
def pass_grade_filter(element):
    return element>50
passed = list(filter(pass_grade_filter, grades))
print(passed)

In [ ]:
## filter with lambda --
passed_filter_lambda = list(filter(lambda element : element>50, list_grades))
print(passed_filter_lambda)

In [ ]:
"""
Q. What will be the output of the code --
1. <filter at memory address>
2. [92, 97, 91]
3. [92, 80, 97, 65, 85, 91]
"""
# code --
demo = [92, 80, 97, 65, 85, 91]
def A_students(element):
    return element > 90
A_pass = list(filter(A_students, demo))
print(A_pass)

## Ans -- Option 2

In [ ]:
"""
Q. Use the filter function to filter the list with
only even numbers.
Use -- lambda, filter, list, %
"""
numbers_list = [ 120 , 31 , 19 , 28 , 512 , 957 , 6321]
even_list = list(filter(lambda i : i%2==0, numbers_list))
print(even_list)

# Python Scripting and Libraries --
1. Scripting basics
2. Python IDE's
3. Jupyter to VScode
4. Importing scripts.

### Script --
1. Python scripts are basically text files with the **.py** extensions that run at once.
2. 

## Numpy -- 
1. What is NumPy? -- It is a free python library that is equipped with the collection of complex mathematical operations and that are suitable for processing statistical data.
2. NumPy Arrays
3. Reshaping, accessing and modifying
4. Slicing and copying
5. Inserting, copying and deleting
6. Array logical indexing

### Intro to NumPy --
1. It is one of the most powerful and popular third-party libraries in Python.
2. **NumPy** is short for **Numerical Python**.
3. NumPy is a must for scentific computing.
4. The main component for NumPy is the N-dimensional array (**ndarray**).

## Why use NumPy??
1. It is **faster** than Python arrays.
2. N-dimensional arrays by nature are more **optimized** and **easier** to work with more complex data.
3. Dozens of **built-in** functions.

## NumPy applications --
1. Scientific domain 
2. Used in dozens of third-party libraries
3. Data Science
4. Machine learning
5. Visualization

## Numpy Array --
1. It is the fundamental unit of NumPy library.
2. It is a multi-dimensional array where all the elements have the same data type.
3. NumPy array can be created using NumPy functions or by converting lists into NumPy arrays.

## Important points nefore using NumPy --
1. It is a standard to **import** NumPy and give it an alias which is **np**. --
    import numpy as np
2. We can also get the **shape** and **data type** of the array element using the *shape* and *dtype* attribute of the NumPy array.
3. NumPy has its own data types which are different from the Python ones.

In [ ]:
"""
converting list to a NumPy array --
"""
import numpy as np
my_list = [1,2,3]
np_arr = np.asarray(my_list)
print(np_arr)

In [ ]:
"""
Getting the shape and data type of a NumPy array --
"""
import numpy as np
my_list = [1,2,3]
np_arr = np.asarray(my_list)
print(np_arr.shape)
print(np_arr.dtype)

In [ ]:
"""
We can also force an array to have a preferred data type --
"""
import numpy as np
my_list = [1,2,3]
np_arr = np.asarray(my_list, dtype=np.int64)

In [ ]:
"""
Creating a NumPy array using built-in funcions ---
"""

In [ ]:
"""
Creating a multi-dimensional array with all '0's --
"""
import numpy as np
np_arr_zeroes = np.zeros((2,5))
print(np_arr_zeroes)

In [ ]:
"""
Creating a multi-dimensional array with all '1's --
"""
import numpy as np
np_arr_ones = np.ones((2,5))
print(np_arr_ones)

In [ ]:
"""
Creating a NumPy array from a ange of values --
"""
import numpy as np
np_arr_range = np.arange((10))
print(np_arr_range)

In [30]:
"""
Creating an array with step --
"""
import numpy as np
np_arr_step = np.arange(start=2, stop=20, step=2)
print(np_arr_step)

## it is not compulsory to write start, stop, step -
np_arr_step2 = np.arange(2,20,2)
print(np_arr_step2)

[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]


In [31]:
"""
Creating a multi-dimensional numpy array of random numbers ---
"""
import numpy as np
np_random = np.random.random((5,5))
print(np_random)

[[0.78257764 0.64768313 0.54521117 0.24925557 0.95367988]
 [0.42935496 0.22380484 0.99710469 0.68368686 0.94860643]
 [0.53095652 0.34530615 0.0540742  0.83956629 0.8076873 ]
 [0.34288669 0.76268733 0.41065963 0.53701566 0.99929249]
 [0.55224175 0.81374147 0.44301851 0.97191347 0.10851264]]


In [32]:
"""
Q. Create a NumPy array with values from 3 to 9
"""
# Ans --
import numpy as np
np_arr = np.arange(3,10)
print(np_arr)

[3 4 5 6 7 8 9]


## Reshaping, accessing and modifying --
### Reshaping --
We can change the shape of an array using **reshape** function. The new shape must have equal number of elements as the old array.
### Accessing & Modifying --
1. We can access and modify specific elements in a 1D NumPy array the same way we did with 1D Python lists.
2. However, accessing and modifying higher dimensional arrays is different from its counterparts.

In [33]:
"""
Changing shape of array using 'reshape'
"""
import numpy as np
np_normal = np.arange((10))
np_arr_reshaped = np.reshape(np_normal, (5,2))
print(np_normal)
print(np_arr_reshaped)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [34]:
"""
Accessing and modifying element of a NumPy array
Same as a 1D list.
"""
import numpy as np
OneD_list = [1,2,3]
np_1D = np.asarray(OneD_list)
print(OneD_list, np_1D)

# accessing elements --
print(OneD_list[1], np_1D[1])

# modifying elements --
OneD_list[2] = 4
np_1D[2] = 4
print(OneD_list[2], np_1D[2])

[1, 2, 3] [1 2 3]
2 2
4 4


In [35]:
"""
Accessing a higher dimension array --
"""
import numpy as np
higher_list = [[1,2,3], [4,5,6], [7,8,9]]
higher_arr = np.array(higher_list)
print(higher_list)
print(higher_arr)

# accessing elements --
print(higher_list[1][2], higher_arr[1,2])

# modifying elements -- 
higher_list[1][2] = 6
higher_arr[1,2] = 6
print(higher_list[1][2], higher_arr[1,2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6 6
6 6


In [36]:
"""
Q. Reshape the given array into a 3*4.
Change the value of the element in the 2nd row, 1st column.
Hint -- NumPy array is zero-indexed
"""
import numpy as np
# given numpy array --
quiz_arr = np.arange(2,14)

# ans --
quiz_reshaped = np.reshape(quiz_arr, (3,4))
print(quiz_reshaped)

quiz_reshaped[1,0]=20
print(quiz_reshaped)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  3  4  5]
 [20  7  8  9]
 [10 11 12 13]]


## Slicing --
[start : end, start : end]

In [37]:
import numpy as np
unsliced_list = [[1,2,3],[4,5,6],[7,8,9]]
unsliced_arr = np.array(unsliced_list)
sliced_arr = unsliced_arr[1:2]
print(sliced_arr)

[[4 5 6]]


## Copying -- 
We should always use the **copy** funciton if we want to work on a subarray without manipulating the original one.

In [38]:
import numpy as np
np_main = np.array([[1,2,3],[4,5,6],[7,8,9]])
np_sub_main = np_main[1:2, 0:]
np_sub_main[0,1]=10
# print(np_main)
# print(np_sub_main)

"""
Above, we also altered the main array too.
To prevent this, we use the copy function.
"""

"""
Copying the array --
"""

# creating a random array first -
np.random.seed(1) # to keep the random array fix
np_to_copy = np.random.random((2,2))
np_copyy = np.copy(np_to_copy[0:2])
print(np_copyy)

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]


In [39]:
"""
Q. What is the output of the following code --

1. [10, 21, 5, 11]
2. [2, 3, 5, 11]
"""
np_quiz = np.array([10, 21, 5, 11])
np_quiz_copy = np_quiz[0:2]
np_quiz_copy[0:2]=[2,3]
print(np_quiz)

# Ans - Option2 because we sliced the array, 
# hence original was also altered.

[ 2  3  5 11]


In [40]:
"""
Q. Copy the given NumPy array and store the copy in 
a new NumPy array.
Change the elements in the slice[2:4, 3:5] with the new Array.
"""
import numpy as np
np_given = np.ones((7,6)) # given array
np_slice = np.zeros((1,2))
np_given_copy = np.copy(np_given)
np_given_copy[2:3, 3:5] = np_slice
print(np_given_copy)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Inserting --
With the **insert** method, we can specify where we want to add new elements.

In [41]:
"""
Inserting example ---
axis=0 -- row, axis=1 -- column
"""
import numpy as np
np_insert = np.array([[1,2],[5,2]])
np_insert2 = np.insert(np_insert, 1, [[5,3],[3,4]], axis=1)
print(np_insert)
print(np_insert2)

[[1 2]
 [5 2]]
[[1 5 3 2]
 [5 3 4 2]]


## Appending --
1. The **append** method is for **concatenating** new elements. So, they are added after the original array elements.
2. If the **axis** parameter is **not used**, the output will be a **1D array**.
3. If the axis parameter is used, the added elements must have the **same shape** as the original array.
4. If **axis = 1**, the added elements must have the **correct shape** with the original array.


In [42]:
"""
Appending example ---
"""
import numpy as np
np_append = np.array([[1,2],[5,2]])
np_append2 = np.append(np_append, [6,1,2])
print(np_append)
print(np_append2)

[[1 2]
 [5 2]]
[1 2 5 2 6 1 2]


In [43]:
"""
Appending example with axis=1 ---
"""
import numpy as np
np_append3 = np.array([[1,2],[5,2]])
np_append4 = np.append(np_append3, [[5,3],[3,4]], axis=1)
print(np_append3)
print(np_append4)

[[1 2]
 [5 2]]
[[1 2 5 3]
 [5 2 3 4]]


## Deleting --

In [44]:
"""
Deleting a 1D array ---
"""
import numpy as np
np_to_delete = np.array([1,2,3,4,5,6,7])
np_to_delete = np.delete(np_to_delete, 0)
print(np_to_delete)
np_to_delete = np.delete(np_to_delete, [1,3])
print(np_to_delete)

"""
the prameters inside the () after the delete function are
the array_name and index, not the element.
"""

[2 3 4 5 6 7]
[2 4 6 7]


'\nthe prameters inside the () after the delete function are\nthe array_name and index, not the element.\n'

In [45]:
"""
We can delete elements from a higher array using the
delete function by specifying the axis parameter.
"""
import numpy as np
np_delete_multi = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np_delete_multi = np.delete(np_delete_multi, 0, axis=1)
print(np_delete_multi)
np_delete_multi = np.delete(np_delete_multi, [1,3], axis=0)
print(np_delete_multi)

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[[2 3]
 [8 9]]


In [46]:
"""
Q. What is the output of the code --

1. [20, 3, 15, 22, 6, 10]

2. [[20,3]
    [15,22]
    [6,10]]
    
3. [20, 3, 15 , 22]

4. Error
"""
import numpy as np
np_ida = np.array([[20,3],[15,22]])
np_ida2 = np.append(np_ida, [6,10])
print(np_ida2)

# Ans -- Option 1 because without the axis keyword
         # we get 1D array as output.

[20  3 15 22  6 10]


In [47]:
"""
Creae 3 copies of the given array.
1. Appned [3,5] to the first copy 
without axis parameter.

2. Insert [[15,21],[41,93]] to the 2nd and 3rd rows 
of the 2nd copy.

3. Delete the first row from the third copy.
"""
import numpy as np
np_givenn = np.array([[20,14], [31,41], [941,678], [1468,121]])
np_copy1 = np.copy(np_givenn)
np_copy2 = np.copy(np_givenn)
np_copy3 = np.copy(np_givenn)

np_copy1 = np.append(np_copy1, [3,4,5])
print(np_copy1)
np_copy2 = np.insert(np_copy2, 1, [[15,21],[41,93]], axis=0)
print(np_copy2)
np_copy3 = np.delete(np_copy3, 0, axis=0)
print(np_copy3)

[  20   14   31   41  941  678 1468  121    3    4    5]
[[  20   14]
 [  15   21]
 [  41   93]
 [  31   41]
 [ 941  678]
 [1468  121]]
[[  31   41]
 [ 941  678]
 [1468  121]]


## Array logical indexing --
Sometimes, we want to select some elements from an array based on a condition.
But the result array is converted to a 1D array.

In [48]:
"""
Logical indexing example ---
"""
import numpy as np
np_to_index = np.array([[1,2,3], [4,5,6], [7,8,9]])
np_indexed = np_to_index[np_to_index>2]
print(np_indexed)

[3 4 5 6 7 8 9]


In [49]:
"""
Q. From the given array, print the values > 30.
"""
##given array - 
import numpy as np
np_quiz_given = np.array([[50,221,12],[21,30,541],[12,31,45]])
np_log = np_quiz_given[np_quiz_given>=30]
print(np_log)

[ 50 221  30 541  31  45]


## Broadcasting --
1. According to NumPy official documentation, **Broadcasting** is how NumPy perfroms arithmetic operations between arrays with different shapes.
2. The **smaller** array is **broadcasted** across the **larger** one.
## Advantages of broadcasting --
1. Much faster than loops.
2. Dosen't create new copies in the memory.

## Broadcasting rules --
1. One of the conditions **must** exist for broadcasting --
    (i) One of the dimensions is **1**.
    (ii) The **trailing** dimensions of both the arrays must match.

In [50]:
import numpy as np
np_1 = np.array([[1,2,3]])
np_2 = np.array([[3,3,5]])
np_3 = np_1*np_2
print(np_3)

[[ 3  6 15]]


In [51]:
import numpy as np
np_4 = np.array([[1,2,3,4,5]])
np_5 = np_4*10
print(np_5)

[[10 20 30 40 50]]


# Pandas ---
1. It is one of the most popular and powerful third-party libraries in Python.
2. **Pandas** comes from **Panel Data**.
3. Pandas is crucial for data manipulation and analysis. We will be using Pandas to manipulate, read, analyze, visualize data and more.
4. Pandas introduces us to two new data structures -- **DataFrame** and **Series**.

## Highlights of Pandas --
1. **DataFrame** is perfect for **tabular** data manipulation.
2. Pandas comes with easy-to-use functions for **interfacing** with text files, excel sheets, SQL databases, and HDF5 binary files.
3. Pandas is also flexible in **labelling** rows and columns.
5. Pandas is highly **integrable** with NumPy, MatPlotLib, and hundreds of poweful libraries.
6. Dozens of data cleaning, manipulation, and analysis functions.

## Pandas Series --

### What is a Pandas Series?
1. They are one-dimensional objects.
2. Capable of holding any data type(integers, strings, floats, point numbers, Python objects, etc.)
3. We can assign an index for each element in the series.

### Series Basic Attributes --
1. shape
2. ndim -- no. of dimensions
3. size
4. values
5. index

In [52]:
"""
Creating a pandas series ---
"""
import pandas as pd
pd_series = pd.Series(data = ['Rishi', 'Thakur', 19, 'CSE'], index = ['F-name', 'L-name', 'age', 'Course'])
print(pd_series)

F-name     Rishi
L-name    Thakur
age           19
Course       CSE
dtype: object


In [53]:
"""
Creating a Pandas series from a numpy array ---
"""
import numpy as np
import pandas as pd
np_to_pd = np.array([1,2,3,7])
series_np = pd.Series(np_to_pd)
print(series_np)

0    1
1    2
2    3
3    7
dtype: int32


In [54]:
"""
Creating a Pandas series from a list ---
"""
import pandas as pd
series_list = pd.Series([65, 10, 90, 54, 65])
print(series_list)

0    65
1    10
2    90
3    54
4    65
dtype: int64


In [55]:
"""
Creating Pandas Series from a dictionary ---
"""
import pandas as pd
n_dict = {'First':30, 'Second':4.05, 'Third':"Orange"}
series_dict = pd.Series(n_dict)
print(series_dict)
print(series_dict['Second'])

First         30
Second      4.05
Third     Orange
dtype: object
4.05


In [56]:
"""
Creating Pandas Series from a Scalar value ---
"""
scalar_value=21
series_scalar = pd.Series(scalar_value, index=[0,1,2,3,4,5])
print(series_scalar)

0    21
1    21
2    21
3    21
4    21
5    21
dtype: int64


In [57]:
"""
Pandas series is like NumPy
"""
print(series_dict.dtype)

object


In [61]:
"""
Converting Pandas series to NumPy array --
"""
import pandas as pd
print(series_dict)
np_series = series_dict.to_numpy()
print(np_series)

First         30
Second      4.05
Third     Orange
dtype: object
[30 4.05 'Orange']


In [62]:
"""
Printing shape of a pandas series ---
"""
print(series_dict.shape)

(3,)


In [63]:
"""
printing no. of dimensions of a pandas series
"""
print(series_dict.ndim)

1


In [64]:
"""
printing the size of a Pandas series
"""
print(series_dict.size)

3


In [65]:
"""
printing values of a pandas series
"""
print(series_dict.values)

[30 4.05 'Orange']


In [66]:
"""
printing the index of a pandas series
"""
print(series_dict.index)

Index(['First', 'Second', 'Third'], dtype='object')


In [69]:
"""
printing the name of a pandas series 
"""
print(series_dict.name)

# we will get none as outpur because we did not
# specify the name of our current series.

None


In [71]:
"""
declaring the name of the series 
"""
import pandas as pd
noName_dict = {'First':30, 'Second':4.05, 'Third':"Orange"}

# converting the dict to a pandas series
noName_series = pd.Series(noName_dict, name='MyDemo')

# now printing the name, we won't get none as the result.
print(noName_series.name)

MyDemo


In [72]:
"""
Q. Are Pandas series similar to NunPy arrays or 
Python dictionaries?
"""
# Ans -- They are similar to both.

'\nQ. Are Pandas series similar to NunPy arrays or \nPython dictionaries?\n'

## Pandas series manipulation --
1. We can **access** elements using the index labels. These labels can be **single** or **multiple**. These labels can be **numerical** or with their **name**.
2. Pandas series is **mutable**.
3. We can drop an element using the **drop** method.
4. We can perform **mathematical** operations on the series, given that these operations are defined for its elements.
5. 

In [82]:
import pandas as pd
di = {'1':1, 'list':[1,2,3], 'tuple':(1,2,3)}
series_di = pd.Series(di)
print(series_di)

1                1
list     [1, 2, 3]
tuple    (1, 2, 3)
dtype: object


In [83]:
"""
Indexing of Pandas series --
"""
print(series_di[0])

# because the object was not dictionary and hence 
# we could call it by index, unlike dictionaries
# where we need the corresponding key.

1


In [84]:
"""
Pandas series are mutable --
"""
series_di['list']=21
print(series_di)

# the output will change the value of the corresponding
# key as pandas series is mutable.

1                1
list            21
tuple    (1, 2, 3)
dtype: object


In [90]:
"""
Droppinh elements from a series ---
"""
dropped = series_di.drop(labels = 'list')
print(dropped)

1                1
tuple    (1, 2, 3)
dtype: object


In [101]:
"""
Performing mathematical operations on Pandas ---
"""
series_1 = pd.Series([1,5,2])
series_2 = pd.Series([10,3,5])

""" adding without builtin Pandas function"""
added_series1 = pd.Series()
for i in range(len(series_1)):
    current1 = series_1[i]
    current2 = series_2[i]
    currentt = current1+current2
    currentt = pd.Series(currentt, index=[i])
    added_series1 = added_series1.append(currentt)
print(f"Without using Pandas : {added_series1}")

""" adding using Pandas function"""
added_series2 = series_1.add(series_2)
print(" ") # for my own purpose (gap)
print(f"Using Pandas : {added_series2}")

Without using Pandas : 0    11
1     8
2     7
dtype: int64
 
Using Pandas : 0    11
1     8
2     7
dtype: int64


C:\Users\rishi\AppData\Local\Temp/ipykernel_14644/2181807650.py:8: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  added_series1 = pd.Series()


In [102]:
"""
How can we subtract two pandas series?
"""
# Ans --
# series_1.sub(series_2)

'\nHow can we subtract two pandas series?\n'

In [105]:
"""
Q. Write a program to add, subtract and multiply the 
given pandas series.
"""
import pandas as pd
pd_series_1 = pd.Series([3,5,2,4,6])
pd_series_2 = pd.Series([2.4,7,3,5,11])

pd_add = pd_series_1.add(pd_series_2)
print(pd_add)
print("  ")
pd_sub = pd_series_1.sub(pd_series_2)
print(pd_sub)
print("  ")
pd_multi = pd_series_1.multiply(pd_series_2)
print(pd_multi)
print(" ")
pd_div = pd_series_1.divide(pd_series_2)
print(pd_div)

0     5.4
1    12.0
2     5.0
3     9.0
4    17.0
dtype: float64
  
0    0.6
1   -2.0
2   -1.0
3   -1.0
4   -5.0
dtype: float64
  
0     7.2
1    35.0
2     6.0
3    20.0
4    66.0
dtype: float64
 
0    1.250000
1    0.714286
2    0.666667
3    0.800000
4    0.545455
dtype: float64


## Pandas DataFrame --
1. A DataFrame is a two-dimensional data structure.
2. It can be imagined as a **dictionary for series** bjects.
3. Each column of the DataFrame is a **Series** object.
4. We can also create a DataFrame by reading a csv file.

### DataFrame basic Attributes --
1. shape
2. ndim
3. size
4. values
5. index
6. **columns**

In [2]:
"""
Creating a DataFrame in python ---
"""
import pandas as pd

corona_tweets = {'username':['ag21a','dg1az','ga1a'],'user_verified':["True","False","False"],'tweets':['Wash hands #covid','Wear a mask #corona','hope it ends soon #quarentine']}
corona_df = pd.DataFrame(corona_tweets, index=['user1','user2','user3'])

In [3]:
"""
Creating DataFrame from a dictionary ---
"""
import pandas as pd
dicto = { "tweet":[1,2,3], "user":['rishi','thakur','arthur'], 'verified':[True, False, False]}

df_dicto = pd.DataFrame(dicto)
print(df_dicto)

# keep in mind, we need to have the same size for all the
# inputs so as to create a DataFrame from a dictionary.

   tweet    user  verified
0      1   rishi      True
1      2  thakur     False
2      3  arthur     False


In [8]:
"""
Creating a DataFrame from a Pandas series ---
"""
import pandas as pd
dicto_series = { "tweet":pd.Series([2,3]), "user":pd.Series(['rishi','thakur','arthur']), 'verified':pd.Series([True, False, False])}

df_dicto_series = pd.DataFrame(dicto_series)
print(df_dicto_series)

# if we remove an element now, still our DataFrame 
# would work properly 

   tweet    user  verified
0    2.0   rishi      True
1    3.0  thakur     False
2    NaN  arthur     False


In [13]:
"""
Creating a DataFrame from a NumPy array
"""
import pandas as pd
import numpy as np
listo = [1,5,2]
df_listo = pd.DataFrame(listo)
print(df_listo)

## the extra '0' in the output is column name, 
# and since we did not define the column name, 
# the default column name was 0

# defining column name --
df_listo_with_column = pd.DataFrame(listo, columns = ['Column1'])
print("  ")
print(df_listo_with_column)

   0
0  1
1  5
2  2
  
   Column1
0        1
1        5
2        2


In [3]:
"""
Creating a DataFrame from a list of dictionaries ---
"""
import pandas as pd
list_dict = [{"a":2, "c":4.5, }, {"b":43, "g":12}]
df_list_dict = pd.DataFrame(list_dict)
print(df_list_dict)

# a,c,b,g acts as column names.
# so, if we give two values to 'a' or 'c' 
# we will get a value inplace of NaN
# this is because the different dictionaries will have
# different index.
list_dict1 = [{"a":2, "c":4.5, }, {"a":43, "c":12}]
df_list_dict1 = pd.DataFrame(list_dict1)
print(df_list_dict1)

     a    c     b     g
0  2.0  4.5   NaN   NaN
1  NaN  NaN  43.0  12.0
    a     c
0   2   4.5
1  43  12.0


In [8]:
"""
Creating a DataFrame from a 2-D Numpy Array ---
"""
import numpy as np
import pandas as pd
npo = 4*np.ones((3,3))
df_npo = pd.DataFrame(npo)
print(df_npo)

     0    1    2
0  4.0  4.0  4.0
1  4.0  4.0  4.0
2  4.0  4.0  4.0


In [10]:
"""
Creating a DataFrame from a Pandas series ---
"""
import pandas as pd
pd_ser = pd.Series([1,2,3,4])
df_pd_ser = pd.DataFrame(pd_ser)
print(df_pd_ser)

   0
0  1
1  2
2  3
3  4


In [2]:
"""
Creating a DataFrame from a csv file ---
"""
import pandas as pd
pd_csv = pd.read_csv('learn.csv')
pd_csv.head()

user_name         user_location  \
0           ᏉᎥ☻լꂅϮ            astroworld   
1    Tom Basile 🇺🇸          New York, NY   
2  Time4fisticuffs      Pewee Valley, KY   
3      ethel mertz  Stuck in the Middle    
4         DIPR-J&K     Jammu and Kashmir   

                                    user_description         user_created  \
0  wednesday addams as a disney princess keepin i...  2017-05-26 05:46:42   
1  Husband, Father, Columnist & Commentator. Auth...  2009-04-16 20:06:23   
2  #Christian #Catholic #Conservative #Reagan #Re...  2009-02-28 18:57:41   
3  #Browns #Indians #ClevelandProud #[]_[] #Cavs ...  2019-03-07 01:45:06   
4  🖊️Official Twitter handle of Department of Inf...  2017-02-12 06:45:15   

   user_followers  user_friends  user_favourites  user_verified  \
0             624           950            18775          False   
1            2253          1677               24           True   
2            9275          9525             7254          False   
3             197           987             1488          False   
4          101009           168              101          False   

                  date                                               text  \
0  2020-07-25 12:27:21  If I smelled the scent of hand sanitizers toda...   
1  2020-07-25 12:27:17  Hey @Yankees @YankeesPR and @MLB - wouldn't it...   
2  2020-07-25 12:27:14  @diane3443 @wdunlap @realDonaldTrump Trump nev...   
3  2020-07-25 12:27:10  @brookbanktv The one gift #COVID19 has give me...   
4  2020-07-25 12:27:08  25 July : Media Bulletin on Novel #CoronaVirus...   

                            hashtags               source  is_retweet  
0                                NaN   Twitter for iPhone       False  
1                                NaN  Twitter for Android       False  
2                        ['COVID19']  Twitter for Android       False  
3                        ['COVID19']   Twitter for iPhone       False  
4  ['CoronaVirusUpdates', 'COVID19']  Twitter for Android       False

In [3]:
"""
Q. Selecting a single column from a DataFrame object returns -
1. NumPy array
2. A DataFrame
3. A dictionary
4. A series
"""
# Ans -- A series

'\nQ. Selecting a single column from a DataFrame object returns -\n1. NumPy array\n2. A DataFrame\n3. A dictionary\n4. A series\n'

### Pandas DataFrame manipulation ---
1. We can access elements, rows or columns of a DataFrame using **labels**.
2. The labels can be either single or multiple.
3. The labels can be numerical or with their name.
4. We can add **rows** using the **append** method.